# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller.xci
# IP: The module: 'controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller.xci
# IP: The module: 'controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/ip/controller/controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
