# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.cache/wt [current_project]
set_property parent.project_path C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/SDK/controller_application/Debug/controller_application.elf
set_property SCOPED_TO_REF controller [get_files -all C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/SDK/controller_application/Debug/controller_application.elf]
set_property SCOPED_TO_CELLS U0/microblaze_I [get_files -all C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/SDK/controller_application/Debug/controller_application.elf]
add_files -quiet C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.runs/controller_synth_1/controller.dcp
set_property used_in_implementation false [get_files C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.runs/controller_synth_1/controller.dcp]
read_vhdl -library xil_defaultlib C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/sources_1/imports/vhdl/main.vhd
read_xdc C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/constr-nexys-4/imports/constraints/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Matthijs/Dropbox/Informatica/Afstuderen/fpga-edu/Vivado/fpga-edu.srcs/constr-nexys-4/imports/constraints/Nexys4_Master.xdc]

synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
